backend: { name: git-gateway, branch: master }

media_folder: static/img
public_folder: /img

publish_mode: editorial_workflow

collections:
  - name: blog
    label: Blog # Used in the UI
    format: json
    folder: assets/content/blog
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor: { preview: true }
    fields: # The fields for each document, usually in front matter
      - { label: Title, name: title, widget: string }
      - { label: "Publish Date", name: date, widget: datetime }
      - { label: Description, name: description, widget: string }
      - { label: Body, name: body, widget: markdown }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }

  - name: galleries
    label: Galleries # Used in the UI
    format: json
    folder: assets/content/gallery
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor: { preview: false }
    fields: # The fields for each document, usually in front matter
      - {
          label: "Gallery",
          name: "thumbnail",
          widget: "image",
          media_library: { config: { multiple: true } },
        }
      - { label: Title, name: title, widget: string }
      - { label: "Publish Date", name: date, widget: datetime }
